name: tommaso
favicon: null
layout_spectrum: 0.21972125093452632
typography_spectrum: 0.0062757390551269054
title: "Tommaso Minnetti's website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6578729306347668
  lightness: 0.2133198077790439
  saturation: 0.14089058176614344
  rhythmicContrast: 0.44011957687325776
purpose: []
