name: tommaso
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30177
title: Tommaso Minnetti
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8c8d2'
    - '#9b9aaa'
    - '#050304'
    - '#553425'
    - '#ffc501'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
